services:
  database:
    image: postgres:16-alpine
    platform: linux/amd64
    env_file:
      - ".env"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $DB_NAME"]
      interval: 5s
      timeout: 2s
      retries: 5

  api:
    env_file:
      - ".env"
    environment:
      - DB_HOST=database
      - DB_PORT=5432
    depends_on:
      database:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src:/home/src

volumes:
  pgdata:
